### PR TITLE
feat: kubelet support --root-dir

### LINKED ISSUE #10: kubelet support --root-dir
**What's it about?**

Support specifying kubelet --root-dir when installing a cluster with kubeadm

**What's the reason why we need it?**

This seems to be a common requirement

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature

### PR DESCRIPTION
**Pull request by lyp256**
### What type of PR is this?

/kind feature

### Which issue(s) this PR fixes:

Fixes #10 

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by x893675** [comment]
please fix ci checks error

**Comment by lyp256** [comment]
@x893675 PTAL

**Pull request merged**
