### PR TITLE
optimize: use addon uninstall steps when delete cluster direct

### LINKED ISSUE #119: addon handling when uninstalling clusters
**What's it about?**
addon handling when uninstalling clusters

**What's the reason why we need it?**
addon handling when uninstalling clusters

I believe this is an important feature for KubeClipper. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

### PR DESCRIPTION
**Pull request by zhuzhenfan**
Signed-off-by: zhuzhenfan <981189503@qq.com>

### What type of PR is this?
/kind feature

### What this PR does / why we need it:
addon handling when uninstalling clusters

### Which issue(s) this PR fixes:

Fixes #119 

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note
None
```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by x893675** [comment]
/retitle optimize: use addon uninstall steps when delete cluster direct

**Review by Xvv-v — APPROVED** [review]

**Pull request merged**
